model_selection:
    model:
      XGBClassifier:
        search_param_grid:
          learning_rate: 
           - 0.1
           - 0.01
           - 0.001
           
          max_depth: 
           - 3
           - 5
           - 7
          
          n_estimators: 
           - 100
           - 200
           - 300
          
          gamma: 
           - 0
           - 0.1
           - 0.2

          
    GaussianNB:
      search_param_grid:
        var_smoothing:
          - 0.5
          - 0.05
          - 0.01
